/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Reports that the process runs. It never touches a dependency.
         */
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Checks PostgreSQL and Redis. Only PostgreSQL is critical: without Redis the API works (fail open), so
         *     it reports `degraded` with 200 and stays in the load balancer.
         */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a customer account
         * @description The address is unique in any letter case and stored as typed. Limited per client address.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Starts a session. Answers with an access token in the shape of an OAuth 2.0 token response, and sets the
         *     session's refresh token in the `cinema_refresh` cookie. If the user then has more sessions than allowed,
         *     the least recently used ones end. Limited per client address and per account address.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the access token
         * @description Trades the refresh token cookie for a new access token, and rotates the refresh token: the answer sets the
         *     new one in the cookie. Within 30 seconds of a rotation, the previous refresh token gets the current one
         *     and the current one is handed out again unchanged, so that tabs refreshing at once, and a client whose
         *     answer got lost, keep their session. Presenting the previous token after that revokes the session.
         *
         *     The body must be the JSON object `{}`. Limited per session.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out of this session
         * @description Ends the session of the refresh token cookie and deletes the cookie. It needs no access token, so it works
         *     after the access token has expired, and it answers 204 whatever the cookie holds, or without one, so it can
         *     be repeated. The body must be the JSON object `{}`.
         *
         *     The access tokens of the session stop working at once.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out of every session
         * @description Ends every session of the caller, on every device, and deletes this client's cookie. The access tokens of
         *     the sessions, this one's included, stop working at once.
         */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's sessions
         * @description Every session of the caller that has not expired, most recently used first: at most 20, so the list has no
         *     pages. A session is used when it logs in or refreshes; requests made with its access tokens do not count.
         *     The session of the access token that asks is marked `current`.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions/{sessionID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * End a session
         * @description Ends one of the caller's sessions, such as the session of a lost phone. It can no longer refresh, and its
         *     access tokens stop working at once. Ending the caller's own session also deletes this client's cookie, as a
         *     logout would.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's account */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List movies */
        get: operations["listMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/movies/{movieID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A movie with its upcoming showtimes
         * @description Lists the showtimes that start within the next 14 days, at most 50.
         */
        get: operations["getMovie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/showtimes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The schedule of a day
         * @description Lists the scheduled showtimes that start on one day in the cinema's time zone, by start time. Served
         *     from a cache: `seats_available` may be up to 10 seconds old; the seat map is fresher. Poll it with
         *     `If-None-Match`.
         */
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/showtimes/{showtimeID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A showtime */
        get: operations["getShowtime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/showtimes/{showtimeID}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The seat map of a showtime
         * @description Every seat with its status and price, by row and number (row `AA` follows `Z`). Served from a cache
         *     that every booking, cancellation, expiry, and sale clears at once; otherwise at most 5 seconds old. A
         *     booking always checks the seats in the database, so a stale map never sells a seat twice.
         *
         *     Poll it with `If-None-Match`: while no seat changes, the answer is `304 Not Modified`.
         */
        get: operations["getSeatMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's bookings
         * @description Newest first. With `status`, only the bookings in those statuses: `status=pending,processing` finds the
         *     caller's unpaid holds in one request. Pass the same `status` with `cursor` for the next page.
         */
        get: operations["listBookings"];
        put?: never;
        /**
         * Hold seats
         * @description Holds the seats for the caller until `expires_at` (15 minutes by default). All or nothing: if any seat
         *     is taken, nothing is held, and `unavailable_seat_ids` lists every taken seat of the request.
         *
         *     A caller has at most one unpaid booking per showtime: a second one is `409 ACTIVE_BOOKING_EXISTS`, whose
         *     `booking_id` names the first, to continue with or cancel. Seats that the caller's own unpaid booking holds
         *     are taken like any other (`SEAT_UNAVAILABLE`). Limited to 20 attempts per caller and minute. With an
         *     `Idempotency-Key`, a retry gets the first answer again instead of a conflict.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{bookingID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A booking of the caller
         * @description Another user's booking is reported as not found, so ids do not leak.
         */
        get: operations["getBooking"];
        put?: never;
        post?: never;
        /**
         * Cancel a booking
         * @description Releases the seats of an unpaid booking. Canceling a booking that is already canceled or expired
         *     succeeds without changes, so a retry gets the same answer.
         */
        delete: operations["cancelBooking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The payment methods that take payments */
        get: operations["listPaymentMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{bookingID}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay for a booking
         * @description Charges a pending booking through a payment method and, on success, sells its seats.
         *
         *     The booking must be pending and its hold not over by the database clock. While the provider works,
         *     the booking is `processing`, so the expiry worker leaves it alone and a charge that completes after the
         *     deadline still gets its seats.
         *
         *     When the provider does not answer in time, the answer is 202: the payment stays `pending`, the booking
         *     `processing`, and the worker settles both within a few minutes; follow `Location`. An `Idempotency-Key`
         *     is required, so a retry after a lost answer gets that answer again instead of paying twice.
         *
         *     The local test provider (development only) takes these tokens: `tok_success`; `tok_slow` (succeeds
         *     after 5 s); `tok_declined`, `tok_insufficient_funds`, `tok_expired_card` (402); `tok_unavailable`
         *     (503); `tok_error` and `tok_timeout` (202).
         */
        post: operations["payBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a movie
         * @description Surrounding space is trimmed from every text field.
         */
        post: operations["createMovie"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/halls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a hall with its seats
         * @description Each row gets seats numbered from 1. The answer lists every seat with its id; halls have no URL of their
         *     own, and showtimes and seat maps show them.
         */
        post: operations["createHall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/showtimes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schedule a showtime
         * @description Puts every seat of the hall on sale: standard and accessible seats at the base price, VIP seats at 1.5
         *     times the base price. The showtime occupies the hall from its start until the movie and 15 minutes of
         *     cleaning are over. A hall cannot host two overlapping showtimes; the database enforces that with an
         *     exclusion constraint, so two admins who schedule the same slot at once cannot both succeed.
         */
        post: operations["createShowtime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details. */
        Problem: {
            /** @constant */
            type: "about:blank";
            /**
             * @description The HTTP status phrase.
             * @example Conflict
             */
            title: string;
            /** @example 409 */
            status: number;
            /** @description What went wrong, for humans. */
            detail?: string;
            /**
             * @description The request path.
             * @example /v1/bookings
             */
            instance?: string;
            /**
             * @description Stable machine-readable code.
             * @example SEAT_UNAVAILABLE
             */
            code: string;
            /** @description The request's `X-Request-ID`. */
            request_id?: string;
            /** @description With `VALIDATION_FAILED`, every invalid field. */
            errors?: components["schemas"]["FieldError"][];
            /** @description With `SEAT_UNAVAILABLE`, the requested seats that are taken. */
            unavailable_seat_ids?: number[];
            /**
             * Format: uuid
             * @description With `ACTIVE_BOOKING_EXISTS`, the caller's unpaid booking for the showtime. Absent if that booking ended
             *     a moment before the answer.
             */
            booking_id?: string;
            /**
             * @description With `PAYMENT_DECLINED`, the provider's reason.
             * @example insufficient_funds
             */
            decline_code?: string;
        };
        FieldError: {
            /** @description The parameter, header, or body field, such as `seat_ids`, `Idempotency-Key`, or `rows[2].label`. */
            field: string;
            /** @example is required */
            message: string;
        };
        Liveness: {
            /** @constant */
            status: "ok";
        };
        Readiness: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            checks: {
                [key: string]: "up" | "down";
            };
        };
        Credentials: {
            /**
             * Format: email
             * @example ann@example.com
             */
            email: string;
            /**
             * @description 8 characters to 72 bytes.
             * @example correct horse battery
             */
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "customer" | "admin";
            /** Format: date-time */
            created_at: string;
        };
        AccessToken: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            /**
             * @description Seconds until the token expires.
             * @example 900
             */
            expires_in: number;
            user: components["schemas"]["User"];
        };
        /**
         * @description The JSON object `{}`.
         * @example {}
         */
        EmptyObject: Record<string, never>;
        /** @description A browser or device that is logged in. */
        Session: {
            /**
             * Format: uuid
             * @description Stable for the session's life; the `sid` of its access tokens.
             */
            id: string;
            /** @description Whether this is the session of the access token that asked. */
            current: boolean;
            /**
             * Format: date-time
             * @description The login.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description The last login or refresh.
             */
            last_used_at: string;
            /**
             * Format: date-time
             * @description When the session ends unless it refreshes before; every refresh moves it, up to 30 days after the login.
             */
            expires_at: string;
            /**
             * @description The `User-Agent` of the last login or refresh; empty if the client sent none.
             * @example Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0
             */
            user_agent: string;
            /**
             * @description The client address of the last login or refresh, IPv4 or IPv6. Absent when unknown.
             * @example 198.51.100.7
             */
            ip?: string;
        };
        SessionList: {
            /** @description Most recently used first. */
            items: components["schemas"]["Session"][];
        };
        Movie: {
            /** Format: int64 */
            id: number;
            /** @example The Last Projectionist */
            title: string;
            description?: string;
            /** @example 118 */
            duration_min: number;
            /** @example PG-13 */
            age_rating?: string;
            /** Format: uri */
            poster_url?: string;
        };
        MovieList: {
            items: components["schemas"]["Movie"][];
            /** @description Absent on the last page. */
            next_cursor?: string;
        };
        MovieDetails: components["schemas"]["Movie"] & {
            upcoming_showtimes: components["schemas"]["Showtime"][];
        };
        MovieRef: {
            /** Format: int64 */
            id: number;
            title: string;
            duration_min: number;
            age_rating?: string;
        };
        HallRef: {
            /** Format: int64 */
            id: number;
            /** @example Hall 1 */
            name: string;
        };
        Showtime: {
            /** Format: int64 */
            id: number;
            movie: components["schemas"]["MovieRef"];
            hall: components["schemas"]["HallRef"];
            /**
             * Format: date-time
             * @example 2026-10-01T19:30:00+02:00
             */
            starts_at: string;
            /**
             * Format: date-time
             * @description When the hall is free again, cleaning included.
             */
            ends_at: string;
            /** @enum {string} */
            status: "scheduled" | "canceled";
            /** @example 1300 */
            base_price_cents: number;
            /** @example USD */
            currency: string;
            seats_available: number;
            seats_total: number;
        };
        Schedule: {
            /** Format: date */
            date: string;
            items: components["schemas"]["Showtime"][];
        };
        /** @enum {string} */
        SeatType: "standard" | "vip" | "accessible";
        /** @enum {string} */
        SeatStatus: "available" | "held" | "sold";
        Seat: {
            /**
             * Format: int64
             * @description The seat id to book.
             */
            id: number;
            /** @example C */
            row: string;
            /** @example 7 */
            number: number;
            type: components["schemas"]["SeatType"];
            /** @example 1300 */
            price_cents: number;
            status: components["schemas"]["SeatStatus"];
        };
        SeatMap: {
            /** Format: int64 */
            showtime_id: number;
            movie: components["schemas"]["MovieRef"];
            hall: components["schemas"]["HallRef"];
            /** Format: date-time */
            starts_at: string;
            currency: string;
            summary: {
                available: number;
                held: number;
                sold: number;
                total: number;
            };
            seats: components["schemas"]["Seat"][];
        };
        CreateBookingRequest: {
            /** Format: int64 */
            showtime_id: number;
            /**
             * @description 1 to 10 distinct seat ids of the showtime, as its seat map lists them.
             * @example [
             *       61,
             *       62
             *     ]
             */
            seat_ids: number[];
        };
        BookedSeat: {
            /** Format: int64 */
            id: number;
            row: string;
            number: number;
            type: components["schemas"]["SeatType"];
            /** @description The price the seat was booked for. */
            price_cents: number;
        };
        /**
         * @description `pending` (seats held until `expires_at`), `processing` (a payment is in flight), `paid` (seats sold),
         *     `expired` (the hold ran out; seats released), `canceled` (by the owner; seats released). `pending` and
         *     `processing` bookings are unpaid and hold their seats; a caller has at most one per showtime.
         * @enum {string}
         */
        BookingStatus: "pending" | "processing" | "paid" | "expired" | "canceled";
        Booking: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["BookingStatus"];
            showtime: {
                /** Format: int64 */
                id: number;
                movie: components["schemas"]["MovieRef"];
                hall: components["schemas"]["HallRef"];
                /** Format: date-time */
                starts_at: string;
            };
            /** @description By row and number. */
            seats: components["schemas"]["BookedSeat"][];
            total_cents: number;
            currency: string;
            /**
             * Format: date-time
             * @description When the hold runs out, in UTC.
             */
            expires_at: string;
            /**
             * Format: date-time
             * @description Only on paid bookings.
             */
            paid_at?: string;
            /** Format: date-time */
            created_at: string;
        };
        BookingList: {
            items: components["schemas"]["Booking"][];
            /** @description Absent on the last page. */
            next_cursor?: string;
        };
        PaymentMethod: {
            /**
             * @description The value of `payment_method`.
             * @example local
             */
            id: string;
            /** @example Test card */
            name: string;
        };
        PaymentMethodList: {
            items: components["schemas"]["PaymentMethod"][];
        };
        PayRequest: {
            /**
             * @description An id from `GET /v1/payment-methods`.
             * @example local
             */
            payment_method: string;
            /**
             * @description Stands for the payment source at the provider; opaque to this API.
             * @example tok_success
             */
            payment_token: string;
        };
        Payment: {
            /**
             * Format: uuid
             * @description Also the idempotency key of every call to the provider.
             */
            id: string;
            /** @enum {string} */
            status: "pending" | "succeeded" | "failed" | "refunded";
            payment_method: string;
            amount_cents: number;
            currency: string;
            /** @description Why a payment failed or was refunded, such as a decline code. */
            failure_reason?: string;
            /** Format: date-time */
            created_at: string;
        };
        PaymentResult: {
            payment: components["schemas"]["Payment"];
            booking: components["schemas"]["Booking"];
        };
        CreateMovieRequest: {
            title: string;
            description?: string;
            duration_min: number;
            age_rating?: string;
            /**
             * Format: uri
             * @description An absolute http or https URL.
             */
            poster_url?: string;
        };
        CreateHallRequest: {
            /**
             * @description Unique.
             * @example Hall 4
             */
            name: string;
            /**
             * @description At most 1 000 seats in all.
             * @example [
             *       {
             *         "label": "A",
             *         "seats": 12,
             *         "type": "accessible"
             *       },
             *       {
             *         "label": "B",
             *         "seats": 14
             *       },
             *       {
             *         "label": "C",
             *         "seats": 14,
             *         "type": "vip"
             *       }
             *     ]
             */
            rows: {
                /**
                 * @description Unique in the hall.
                 * @example A
                 */
                label: string;
                seats: number;
                /** @default standard */
                type: components["schemas"]["SeatType"];
            }[];
        };
        HallSeat: {
            /**
             * Format: int64
             * @description The seat id of every showtime in the hall.
             */
            id: number;
            row: string;
            number: number;
            type: components["schemas"]["SeatType"];
        };
        Hall: {
            /** Format: int64 */
            id: number;
            name: string;
            seats_total: number;
            seats: components["schemas"]["HallSeat"][];
        };
        CreateShowtimeRequest: {
            /** Format: int64 */
            movie_id: number;
            /** Format: int64 */
            hall_id: number;
            /**
             * Format: date-time
             * @description In the future and at most 366 days ahead, with a UTC offset.
             * @example 2026-10-01T19:30:00+02:00
             */
            starts_at: string;
            /** @example 1300 */
            base_price_cents: number;
        };
        /**
         * @description Printable ASCII.
         * @example 0199a1f0-9e3a-7f4c-9d5a-7b2e4f3a6c99
         */
        IdempotencyKey: string;
    };
    responses: {
        /** @description The content has not changed since the `ETag` in `If-None-Match`. No body. */
        NotModified: {
            headers: {
                ETag: components["headers"]["ETag"];
                "Cache-Control": components["headers"]["Cache-Control-No-Cache"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /**
         * @description - `VALIDATION_FAILED`: invalid parameters or fields; `errors` lists every one of them.
         *     - `MALFORMED_BODY`: the body is not one JSON object, or has unknown fields.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Bad Request",
                 *       "status": 400,
                 *       "detail": "The request has invalid parameters.",
                 *       "instance": "/v1/admin/halls",
                 *       "code": "VALIDATION_FAILED",
                 *       "request_id": "0199a1f0-7c1e-7d2a-9b3e-5f0c2d1e4a77",
                 *       "errors": [
                 *         {
                 *           "field": "name",
                 *           "message": "is required"
                 *         },
                 *         {
                 *           "field": "rows[1].seats",
                 *           "message": "must be between 1 and 100"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `UNAUTHENTICATED` (no bearer token), `INVALID_TOKEN` (also when the token's session has ended), or
         *     `TOKEN_EXPIRED`.
         */
        Unauthorized: {
            headers: {
                "WWW-Authenticate": components["headers"]["WWW-Authenticate"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `FORBIDDEN`: the caller is not an admin. */
        Forbidden: {
            headers: {
                "WWW-Authenticate": components["headers"]["WWW-Authenticate"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `MOVIE_NOT_FOUND`, `SHOWTIME_NOT_FOUND`, or `BOOKING_NOT_FOUND`. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `BODY_TOO_LARGE`: the body is larger than 64 KiB. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `UNSUPPORTED_MEDIA_TYPE`: the body must be sent as `application/json`. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `RATE_LIMITED`: too many attempts; retry after `Retry-After`. */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `INTERNAL`: an unexpected error. The details are in the server log under `request_id`. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        MovieID: number;
        ShowtimeID: number;
        BookingID: string;
        /** @description The `id` of a session from `GET /v1/auth/sessions`. */
        SessionID: string;
        /** @description Page size. */
        Limit: number;
        /** @description The `next_cursor` of the previous page. */
        Cursor: string;
        /**
         * @description The `ETag` of an earlier answer, or several separated by commas. When one matches the current content,
         *     the answer is `304 Not Modified`. Weak and strong forms of a tag match alike.
         */
        IfNoneMatch: string;
        /**
         * @description A key of the caller's choice, such as a UUID. A retry with the same key and body gets the stored answer
         *     for 24 hours, with `Idempotent-Replayed: true`.
         */
        IdempotencyKeyOptional: components["schemas"]["IdempotencyKey"];
        /**
         * @description A key of the caller's choice, such as a UUID, new for every payment attempt. A retry with the same key
         *     and body gets the stored answer for 24 hours, with `Idempotent-Replayed: true`.
         */
        IdempotencyKeyRequired: components["schemas"]["IdempotencyKey"];
    };
    requestBodies: never;
    headers: {
        /** @description The URL of the resource. */
        Location: string;
        /** @description Seconds to wait before retrying the same request. */
        "Retry-After": number;
        /** @description `true` when the answer repeats the stored answer of an earlier request with the same key. */
        "Idempotent-Replayed": "true";
        /** @description The bearer challenge (RFC 6750), with `error="invalid_token"` for a rejected token. */
        "WWW-Authenticate": string;
        /** @description Always `no-store` (RFC 6749 §5.1). */
        "Cache-Control-No-Store": "no-store";
        /** @description Always `no-cache`. Browsers and caches may keep the answer, but ask again, with its `ETag`, every time. */
        "Cache-Control-No-Cache": "no-cache";
        /** @description A weak tag of the content: the unpadded base64url SHA-256 of the body. Send it back in `If-None-Match`. */
        ETag: string;
        /**
         * @description The session's current refresh token. `Max-Age` runs until the session expires; `Secure` is left out only
         *     when the API is configured for plain-HTTP development.
         */
        "Set-Refresh-Cookie": string;
        /** @description Deletes the refresh token cookie. */
        "Clear-Refresh-Cookie": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to take traffic, possibly without Redis. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description PostgreSQL is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "unavailable",
                     *       "checks": {
                     *         "postgres": "down",
                     *         "redis": "up"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description The account. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description `EMAIL_TAKEN`: an account with this address exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description The access token and the account; the refresh token is in the cookie. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["Cache-Control-No-Store"];
                    "Set-Cookie": components["headers"]["Set-Refresh-Cookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description `INVALID_CREDENTIALS`: the address or the password is wrong. The answer does not say which. */
            401: {
                headers: {
                    "WWW-Authenticate": components["headers"]["WWW-Authenticate"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyObject"];
            };
        };
        responses: {
            /** @description A new access token and the account; the session's current refresh token is in the cookie. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["Cache-Control-No-Store"];
                    "Set-Cookie": components["headers"]["Set-Refresh-Cookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            /**
             * @description `REFRESH_INVALID`: no cookie, or its token is malformed, unknown, expired, revoked, or was already
             *     used. The answer does not say which, and deletes the cookie. Log in again.
             */
            401: {
                headers: {
                    "Set-Cookie": components["headers"]["Clear-Refresh-Cookie"];
                    "WWW-Authenticate": components["headers"]["WWW-Authenticate"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyObject"];
            };
        };
        responses: {
            /** @description The session is over, if there was one. */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["Clear-Refresh-Cookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session of the caller is over. */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["Clear-Refresh-Cookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The `id` of a session from `GET /v1/auth/sessions`. */
                sessionID: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is over. */
            204: {
                headers: {
                    /** @description Only when the caller ended its own session; deletes the refresh token cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /**
             * @description `SESSION_NOT_FOUND`: the caller has no such session. A session of another user, and one that has
             *     already ended, get the same answer.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listMovies: {
        parameters: {
            query?: {
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description The `next_cursor` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of movies, by id. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieList"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getMovie: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movieID: components["parameters"]["MovieID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The movie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieDetails"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getSchedule: {
        parameters: {
            query?: {
                /** @description The day, `YYYY-MM-DD`. Today in the cinema's time zone when absent. */
                date?: string;
                /** @description Only this movie's showtimes. */
                movie_id?: number;
            };
            header?: {
                /**
                 * @description The `ETag` of an earlier answer, or several separated by commas. When one matches the current content,
                 *     the answer is `304 Not Modified`. Weak and strong forms of a tag match alike.
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The schedule. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["Cache-Control-No-Cache"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getShowtime: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                showtimeID: components["parameters"]["ShowtimeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The showtime with its live seat counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Showtime"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getSeatMap: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description The `ETag` of an earlier answer, or several separated by commas. When one matches the current content,
                 *     the answer is `304 Not Modified`. Weak and strong forms of a tag match alike.
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                showtimeID: components["parameters"]["ShowtimeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The seat map. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["Cache-Control-No-Cache"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatMap"];
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listBookings: {
        parameters: {
            query?: {
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description The `next_cursor` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                /**
                 * @description Booking statuses, separated by commas. The parameter may also be repeated
                 *     (`status=pending&status=processing`). Absent or empty: every status. An unknown status is
                 *     `400 VALIDATION_FAILED` naming `status`.
                 * @example [
                 *       "pending",
                 *       "processing"
                 *     ]
                 */
                status?: components["schemas"]["BookingStatus"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of bookings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description A key of the caller's choice, such as a UUID. A retry with the same key and body gets the stored answer
                 *     for 24 hours, with `Idempotent-Replayed: true`.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyOptional"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The booking, with its seats held. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    "Idempotent-Replayed": components["headers"]["Idempotent-Replayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description `SHOWTIME_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description - `SEAT_UNAVAILABLE`: seats are held or sold; `unavailable_seat_ids` lists them.
             *     - `SEAT_BUSY`: another booking kept the seats locked for too long; retry after `Retry-After`.
             *     - `BOOKING_BUSY`: another request of the caller for this showtime is running; retry.
             *     - `ACTIVE_BOOKING_EXISTS`: the caller has an unpaid booking for this showtime; `booking_id` names it
             *       (absent if it ended a moment before the answer).
             *     - `SHOWTIME_NOT_BOOKABLE`: the showtime has started or was canceled.
             *     - `IDEMPOTENCY_IN_PROGRESS`: the first request with this key is still running; retry.
             */
            409: {
                headers: {
                    "Retry-After": components["headers"]["Retry-After"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            /**
             * @description - `UNKNOWN_SEAT`: seats that are not part of the showtime.
             *     - `IDEMPOTENCY_KEY_REUSED`: the key was used for a request with another body.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingID: components["parameters"]["BookingID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The booking. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingID: components["parameters"]["BookingID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The booking holds no seats. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description - `BOOKING_NOT_CANCELABLE`: a payment is in progress, or the booking is paid.
             *     - `BOOKING_BUSY`: another request holds the booking; retry after `Retry-After`.
             */
            409: {
                headers: {
                    "Retry-After": components["headers"]["Retry-After"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listPaymentMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The enabled payment providers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "local",
                     *           "name": "Test card"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["PaymentMethodList"];
                };
            };
        };
    };
    payBooking: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description A key of the caller's choice, such as a UUID, new for every payment attempt. A retry with the same key
                 *     and body gets the stored answer for 24 hours, with `Idempotent-Replayed: true`.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                bookingID: components["parameters"]["BookingID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayRequest"];
            };
        };
        responses: {
            /** @description Paid; the seats are sold. */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["Idempotent-Replayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResult"];
                };
            };
            /** @description The outcome is not known yet. The payment is `pending` and the booking `processing`. */
            202: {
                headers: {
                    Location: components["headers"]["Location"];
                    "Idempotent-Replayed": components["headers"]["Idempotent-Replayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResult"];
                };
            };
            /** @description `VALIDATION_FAILED`, also for a missing or malformed `Idempotency-Key`, or `MALFORMED_BODY`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `PAYMENT_DECLINED`: the provider declined; `decline_code` says why. The booking is pending again. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "about:blank",
                     *       "title": "Payment Required",
                     *       "status": 402,
                     *       "detail": "the payment was declined (insufficient_funds); nothing was charged",
                     *       "instance": "/v1/bookings/0199a1f0-7c1e-7d2a-9b3e-5f0c2d1e4a77/payments",
                     *       "code": "PAYMENT_DECLINED",
                     *       "request_id": "0199a1f0-8d2f-7e3b-8c4f-6a1d3e2f5b88",
                     *       "decline_code": "insufficient_funds"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            404: components["responses"]["NotFound"];
            /**
             * @description - `PAYMENT_IN_PROGRESS`: another payment of the booking is in flight.
             *     - `BOOKING_ALREADY_PAID`, `BOOKING_CANCELED`.
             *     - `BOOKING_BUSY`: another request holds the booking; retry after `Retry-After`.
             *     - `PAYMENT_REFUNDED`: the charge went through only after the booking had stopped waiting for it,
             *       and was refunded.
             *     - `IDEMPOTENCY_IN_PROGRESS`: the first request with this key is still running; retry.
             */
            409: {
                headers: {
                    "Retry-After": components["headers"]["Retry-After"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `BOOKING_EXPIRED`: the hold ran out; the seats may be someone else's now. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            /**
             * @description - `PAYMENT_METHOD_UNAVAILABLE`: the method is unknown or disabled; see `GET /v1/payment-methods`.
             *     - `IDEMPOTENCY_KEY_REUSED`: the key was used for a request with another body.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            /**
             * @description `PAYMENT_PROVIDER_UNAVAILABLE`: the provider refused the request. Nothing was charged, and the
             *     booking is pending again; retry after `Retry-After` with a new `Idempotency-Key`.
             */
            503: {
                headers: {
                    "Retry-After": components["headers"]["Retry-After"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createMovie: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMovieRequest"];
            };
        };
        responses: {
            /** @description The movie. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movie"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    createHall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHallRequest"];
            };
        };
        responses: {
            /** @description The hall and its seats, by row and number. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hall"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description `HALL_NAME_TAKEN`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    createShowtime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShowtimeRequest"];
            };
        };
        responses: {
            /** @description The showtime. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Showtime"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description `MOVIE_NOT_FOUND` or `HALL_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `HALL_OVERLAP`: another scheduled showtime occupies the hall at an overlapping time. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
}
